<?php

?>
<form id="<?php echo T6; ?>formData" name="<?php echo T6; ?>formData" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="width: 30%;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"  aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title"><?php  echo LABEL_15; ?></h4>
            </div>
            <div class="modal-body smart-form">
                <div style="position: relative;margin-bottom: 30px">
                    <button type="button" class="btn btn-default pull-left"><i class="fa fa-plus" style="padding: 5px;"></i></button><span class="pull-left">&nbsp;</span>
                    <button type="button" class="btn btn-default pull-left"><i class="fa fa-minus" style="padding: 5px;"></i></button>
                    <button type="button" class="btn btn-default pull-right"><i class="fa fa-caret-down" style="padding: 5px;"></i></button><span class="pull-right">&nbsp;</span>
                    <button type="button" class="btn btn-default pull-right"><i class="fa fa-caret-up" style="padding: 5px;"></i></button>
                </div>
                <table class="table table-bordered table-striped table-condensed table-hover has-tickbox">
                    <thead>
                        <tr>
                            <th style="width: 50%">Etiqueta del elemento</th>
                            <th style="width: 50%">Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <label class="input">
                                    <input type="text" id="" name="">
                                </label>
                            </td>
                            <td>
                                <label class="input">
                                    <input type="text" id="" name="">
                                </label>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button id="<?php echo T6; ?>btnGacepta" type="submit" class="btn txt-color-white bg-color-blueDark">
                    <i class="fa fa-check"></i> <?php echo BTN_ACEP; ?>
                </button>
                <button type="button" class="btn btn-default xClose">
                    <i class="fa fa-ban"></i> <?php echo BTN_CLOSE; ?>
                </button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</form>
<!-- si no riene permiso se anula submit desde cualquier input -->
    <script>
        simpleScript.noSubmit('#<?php echo T6; ?>formData');
    </script>
<script>
    $('.xhelp').tooltip({placement: 'right'});
    $('#<?php echo T6; ?>formData').validate({
        // Rules for form validation
        rules: {
            <?php echo T6; ?>lst_aplicacion: {
                required: true
            },
            <?php echo T6; ?>txt_descripcion: {
                required: true,
                regular: true,
                minlength: 3
            }
        },
        // Do not change code below
        errorPlacement: function(error, element) {
            error.insertAfter(element.parent());
        },
        submitHandler: function() {
            modulo.postNuevoModulo();
        }
    });
    /*para hacer evento invisible*/
simpleScript.removeAttr.click({
    container: '#<?php echo T6; ?>formData',
    typeElement: 'button'
});
</script>
